--------------------------------------------------------
--  DDL for Table SCP_TAB00_DATA
--------------------------------------------------------
-- SCP_TAB01_SCARTI
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SCPT.SCP_TAB00_DATA';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; 
	  END IF;
END;
/
-- creo tabella 00
  CREATE TABLE SCPT.SCP_TAB00_DATA
   (	CF VARCHAR2(100 BYTE), 
	NOME VARCHAR2(100 BYTE),
	COGNOME VARCHAR2(100 BYTE),
	SALARIO VARCHAR2(100 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY SCP_DATA_DIR
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
BADFILE SCP_BAD_DIR : 'Bad_scarti_00'
NODISCARDFILE
LOGFILE SCP_LOG_DIR : 'Log_scarti_00'
skip 1
FIELDS
    TERMINATED BY ';'
    MISSING FIELD VALUES ARE NULL                               )
      LOCATION
       ( SCP_DATA_DIR:'dati.csv'
       )
    )
REJECT LIMIT 10;


EXECUTE LOAD_TO_TAB01_DINAMIC;

EXIT;


